#ifndef _BTSTACK_DEMO_H_
#define _BTSTACK_DEMO_H_

#include "typedef.h"

// #define LE_INIT_ENABLE
// #define LE_DATA_LENGTH_EXTENSION_ENABLE
// #define LE_CENTRAL_ENABLE
// #define LE_PERIPHERAL_ENABLE

#define CLASSIC_INIT_ENABLE
#define CLASSIC_RESPONDING_SIDE
// #define CLASSIC_INITIATING_SIDE

enum {
    HCI_STATE_OFF = 0,
    HCI_STATE_INITIALIZING,
    HCI_STATE_WORKING,
    HCI_STATE_HALTING,
    HCI_STATE_SLEEPING,
    HCI_STATE_FALLING_ASLEEP
} ;


enum hci_init_state {

    HCI_INIT_SEND_RESET = 0,
    HCI_INIT_W4_SEND_RESET,

    HCI_INIT_READ_BD_ADDR,
    HCI_INIT_W4_READ_BD_ADDR,

    HCI_INIT_READ_BUFFER_SIZE,
    HCI_INIT_W4_READ_BUFFER_SIZE,

    HCI_INIT_SEND_READ_LOCAL_VERSION_INFORMATION,
    HCI_INIT_W4_SEND_READ_LOCAL_VERSION_INFORMATION,

    HCI_INIT_SEND_READ_LOCAL_NAME,
    HCI_INIT_W4_SEND_READ_LOCAL_NAME,

    HCI_INIT_SET_EVENT_MASK,
    HCI_INIT_W4_SET_EVENT_MASK,

    // HCI_INIT_WRITE_SIMPLE_PAIRING_MODE,
    // HCI_INIT_W4_WRITE_SIMPLE_PAIRING_MODE,

    // HCI_INIT_WRITE_PAGE_TIMEOUT,
    // HCI_INIT_W4_WRITE_PAGE_TIMEOUT,

    // HCI_INIT_WRITE_CLASS_OF_DEVICE,
    // HCI_INIT_W4_WRITE_CLASS_OF_DEVICE,

    // HCI_INIT_WRITE_LOCAL_NAME,
    // HCI_INIT_W4_WRITE_LOCAL_NAME,

    // HCI_INIT_WRITE_EIR_DATA,
    // HCI_INIT_W4_WRITE_EIR_DATA,

    // HCI_INIT_WRITE_INQUIRY_MODE,
    // HCI_INIT_W4_WRITE_INQUIRY_MODE,

    // HCI_INIT_WRITE_SCAN_ENABLE,
    // HCI_INIT_W4_WRITE_SCAN_ENABLE,

#ifdef LE_INIT_ENABLE
    HCI_INIT_LE_READ_BUFFER_SIZE,
    HCI_INIT_W4_LE_READ_BUFFER_SIZE,
    // HCI_INIT_WRITE_LE_HOST_SUPPORTED,
    // HCI_INIT_W4_WRITE_LE_HOST_SUPPORTED,
    HCI_INIT_LE_SET_EVENT_MASK,
    HCI_INIT_W4_LE_SET_EVENT_MASK,

#ifdef LE_PERIPHERAL_ENABLE
    HCI_INIT_LE_SET_ADV_PARAMETERS,
    HCI_INIT_W4_LE_SET_ADV_PARAMETERS,

    HCI_INIT_LE_SET_ADV_DATA,
    HCI_INIT_W4_LE_SET_ADV_DATA,

    HCI_INIT_LE_SET_SCAN_RESPONSE_DATA,
    HCI_INIT_W4_LE_SET_SCAN_RESPONSE_DATA,

    HCI_INIT_LE_SET_ADV_ENABLE,
    HCI_INIT_W4_LE_SET_ADV_ENABLE,
#endif

#ifdef LE_CENTRAL_ENABLE
    HCI_INIT_LE_SET_SCAN_PARAMETERS,
    HCI_INIT_W4_LE_SET_SCAN_PARAMETERS,

    HCI_INIT_LE_SET_SCAN_ENABLE,
    HCI_INIT_W4_LE_SET_SCAN_ENABLE,
#endif

#endif

#ifdef CLASSIC_INIT_ENABLE
    HCI_INIT_WRITE_CLASS_OF_DEVICE,
    HCI_INIT_W4_WRITE_CLASS_OF_DEVICE,

    HCI_INIT_WRITE_LOCAL_NAME,
    HCI_INIT_W4_WRITE_LOCAL_NAME,

    HCI_INIT_WRITE_EIR_DATA,
    HCI_INIT_W4_WRITE_EIR_DATA,

#ifdef CLASSIC_RESPONDING_SIDE
    HCI_INIT_WRITE_SCAN_ENABLE,
    HCI_INIT_W4_WRITE_SCAN_ENABLE,
#endif

#ifdef CLASSIC_INITIATING_SIDE
    HCI_INIT_WRITE_CREATE_CONNECTION,
    HCI_INIT_W4_WRITE_CREATE_CONNECTION,
#endif

    HCI_INIT_ACL_DATA_TEST,
    HCI_INIT_SEND_ACL_DATA,
    HCI_INIT_RECEIVE_ACL_DATA,

#endif

    HCI_INIT_DONE,
};

enum {
    BTSTACK_HCI_EVENT = (Q_USER + 1),
    BTSTACK_HCI_ACL,
    BTSTACK_HCI_SOC,
    BTSTACK_TASK_READY,
    BTSTACK_TASK_EXIT,
};

#define HCI_MAX_TOTAL_PAYLOAD   0x800
#define HCI_MAX_EVENT_PAYLOAD   0x200

#endif
